version: '3.8'
services:

  orders-app:

    image: pl.dominiak.orders/zamowienia-app:latest
    container_name: zamowienia_processor

    ports:
      - "8080:8080"


    volumes:

      - ./zadania_wejsciowe:/app/input/orders


      - ./wyniki_wyjsciowe:/app/output/results



    environment:
      - JAVA_OPTS=-Xmx512m